#ifndef KCDK_PACKET_H
#define KCDK_PACKET_H

#include <stdint.h>
#include "kcdk_job.h"
#include "kcdk_usart.h"

#define KCDK_PACKET_LENGTH_SYNC_1ST sizeof(uint8_t)
#define KCDK_PACKET_LENGTH_SYNC_2ND sizeof(uint8_t)
#define KCDK_PACKET_LENGTH_SYNC (KCDK_PACKET_LENGTH_SYNC_1ST + KCDK_PACKET_LENGTH_SYNC_2ND)
#define KCDK_PACKET_LENGTH_HEADER sizeof(uint8_t)
#define KCDK_PACKET_LENGTH_SOURCE sizeof(uint64_t)
#define KCDK_PACKET_LENGTH_DESTINATION KCDK_PACKET_LENGTH_SOURCE
#define KCDK_PACKET_LENGTH_CHECKSUM sizeof(uint8_t)
#define KCDK_PACKET_LENGTH_NONCE sizeof(uint32_t)
#define KCDK_PACKET_LENGTH_ERROR_CODE sizeof(uint8_t)
#define KCDK_PACKET_LENGTH_OLD_HASH 40
#define KCDK_PACKET_LENGTH_EXPECTED_HASH 20
#define KCDK_PACKET_LENGTH_DIFFICULTY sizeof(uint32_t)
#define KCDK_PACKET_LENGTH_BASE (KCDK_PACKET_LENGTH_SYNC + KCDK_PACKET_LENGTH_HEADER + KCDK_PACKET_LENGTH_DESTINATION + KCDK_PACKET_LENGTH_CHECKSUM)
#define KCDK_PACKET_LENGTH_ACK KCDK_PACKET_LENGTH_BASE
#define KCDK_PACKET_LENGTH_ERR (KCDK_PACKET_LENGTH_BASE + KCDK_PACKET_LENGTH_ERROR_CODE)
#define KCDK_PACKET_LENGTH_IDN KCDK_PACKET_LENGTH_BASE
#define KCDK_PACKET_LENGTH_JRQ KCDK_PACKET_LENGTH_BASE
#define KCDK_PACKET_LENGTH_JOB (KCDK_PACKET_LENGTH_BASE + KCDK_PACKET_LENGTH_OLD_HASH + KCDK_PACKET_LENGTH_EXPECTED_HASH + KCDK_PACKET_LENGTH_DIFFICULTY)
#define KCDK_PACKET_LENGTH_JRS (KCDK_PACKET_LENGTH_BASE + KCDK_PACKET_LENGTH_NONCE)
#define KCDK_PACKET_OFFSET_SYNC_1ST 0
#define KCDK_PACKET_OFFSET_SYNC_2ND (KCDK_PACKET_OFFSET_SYNC_1ST + KCDK_PACKET_LENGTH_SYNC_1ST)
#define KCDK_PACKET_OFFSET_HEADER (KCDK_PACKET_OFFSET_SYNC_2ND + KCDK_PACKET_LENGTH_SYNC_2ND)
#define KCDK_PACKET_OFFSET_SOURCE (KCDK_PACKET_OFFSET_HEADER + KCDK_PACKET_LENGTH_HEADER)
#define KCDK_PACKET_OFFSET_DESTINATION KCDK_PACKET_OFFSET_SOURCE
#define KCDK_PACKET_OFFSET_CHECKSUM (KCDK_PACKET_OFFSET_SOURCE + KCDK_PACKET_LENGTH_SOURCE)
#define KCDK_PACKET_OFFSET_NONCE (KCDK_PACKET_OFFSET_CHECKSUM + KCDK_PACKET_LENGTH_CHECKSUM)
#define KCDK_PACKET_OFFSET_ERROR_CODE KCDK_PACKET_OFFSET_NONCE
#define KCDK_PACKET_OFFSET_OLD_HASH KCDK_PACKET_OFFSET_NONCE
#define KCDK_PACKET_OFFSET_EXPECTED_HASH (KCDK_PACKET_OFFSET_OLD_HASH + KCDK_PACKET_LENGTH_OLD_HASH)
#define KCDK_PACKET_OFFSET_DIFFICULTY (KCDK_PACKET_OFFSET_EXPECTED_HASH + KCDK_PACKET_LENGTH_EXPECTED_HASH)
#define KCDK_PACKET_VALUE_SYNC_SLAVE_1ST 0x4B
#define KCDK_PACKET_VALUE_SYNC_SLAVE_2ND 0x6B
#define KCDK_PACKET_VALUE_SYNC_MASTER_1ST 0x6B
#define KCDK_PACKET_VALUE_SYNC_MASTER_2ND 0x4B
#define KCDK_PACKET_VALUE_HEADER_ACK 0x41
#define KCDK_PACKET_VALUE_HEADER_ERR 0x45
#define KCDK_PACKET_VALUE_HEADER_IDN 0x49
#define KCDK_PACKET_VALUE_HEADER_JRQ 0x52
#define KCDK_PACKET_VALUE_HEADER_JOB 0x4A
#define KCDK_PACKET_VALUE_HEADER_JRS 0x56
#define KCDK_PACKET_VALUE_CHECKSUM_PRE 0x69

uint8_t kcdk_packet_find_sync(kcdk_usart_context_t *usart_ctx);
uint8_t kcdk_packet_get_header(kcdk_usart_context_t *usart_ctx);
uint8_t kcdk_packet_check_destination(kcdk_usart_context_t *usart_ctx);
void kcdk_packet_parse_job(kcdk_usart_context_t *usart_ctx, kcdk_job_context_t *job_ctx);
void kcdk_packet_prepare(kcdk_job_context_t *job_ctx);
void kcdk_packet_checksum_calculate(kcdk_job_context_t *job_ctx);
uint8_t kcdk_packet_checksum_validate(kcdk_usart_context_t *usart_ctx, uint8_t length);
void kcdk_packet_send_idn(kcdk_job_context_t *job_ctx);
void kcdk_packet_send_jrq(kcdk_job_context_t *job_ctx);
void kcdk_packet_send_jrs(kcdk_job_context_t *job_ctx);
void kcdk_packet_send_ack(kcdk_job_context_t *job_ctx);
void kcdk_packet_resend(kcdk_job_context_t *job_ctx);

#endif
